#!/bin/bash
# for linux build
gcc -Wall -Wno-pointer-sign -g -IInclude -Llib/Linux src/*.c -lgoodbrew -lSDLFontCache -lm -lpthread `sdl2-config --cflags --libs` -lSDL2_image -lSDL2_ttf -Llib -llua -lcurl -ldl -lcrypto -o bin/a.exe
