#!/bin/bash
# for linux build
gcc -g -IInclude -Llib/Linux src/*.c -lGeneralGood -lSDLFontCache -lm -lpthread `sdl2-config --cflags --libs` -lSDL2_image -lSDL2_ttf -Llib -llua -lcurl -ldl -o bin/a.exe